spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.208:3306/blog?serverTimezone=UTC&characterEncoding=UTF-8
    username: tester
    password: dkansk
  flyway:
    baseline-on-migrate: true
    enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialects: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        default_batch_fetch_size: 1000
      jdbc:
        lob:
          non_contextual_creation: true

